### ISSUE TITLE
I encountered some problems, want to ask about.

### ISSUE THREAD

**Issue by RonanDex** [ubergarm/l2tp-ipsec-vpn-client#1]
VPN connection, the use of ip a show ppp0 is OK.
Use `sudo ip route add 1.2.3.4 via 192.0.2.1 dev ppp0 ` forwarding a single address is no problem.

But use
```
Sudo ip route add default via 192.0.2.1 dev ppp0
# Or
Sudo route add-net default gw 192.0.2.1 dev ppp0
# And delete old default routes like
Sudo route del -net default gw 10.0.1.1 dev eth0
```
There will be an error that the buffer is not available. Why is that?

I use the centos7

<img width="684" alt="2017-07-16 11 16 03" src="https://user-images.githubusercontent.com/4251021/28248924-7f86406e-6a7f-11e7-8820-75c0f3624cf4.png">

**Comment by RonanDex** [comment]
<img width="356" alt="2017-07-16 11 37 27" src="https://user-images.githubusercontent.com/4251021/28248946-c41e8c0e-6a7f-11e7-8a17-84784129ac04.png">

**Comment by ubergarm** [comment]
I don't use CentOS so sorry I can't answer. It may be that the `ip` or `route` commands vary slightly in their usage. Or perhaps I have a mistake in my README.

`route` is deprecated and replaced by `ip` I believe, so perhaps check `map ip` on your machine.

Good luck!
